//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP_SalesOrderManager.sr_InvDiscDetails {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", ConfigurationName="sr_InvDiscDetails.RechnungsrabattDetails_Port")]
    public interface RechnungsrabattDetails_Port {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappername (Read_Result) von Nachricht "Read_Result" nicht mit dem Standardwert (Read) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Read_Result Read(AMP_SalesOrderManager.sr_InvDiscDetails.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Read_Result> ReadAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Read request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappername (ReadByRecId_Result) von Nachricht "ReadByRecId_Result" nicht mit dem Standardwert (ReadByRecId) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId_Result ReadByRecId(AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId_Result> ReadByRecIdAsync(AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappername (ReadMultiple_Result) von Nachricht "ReadMultiple_Result" nicht mit dem Standardwert (ReadMultiple) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple_Result ReadMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple_Result> ReadMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappername (IsUpdated_Result) von Nachricht "IsUpdated_Result" nicht mit dem Standardwert (IsUpdated) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated_Result IsUpdated(AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated_Result> IsUpdatedAsync(AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappername (GetRecIdFromKey_Result) von Nachricht "GetRecIdFromKey_Result" nicht mit dem Standardwert (GetRecIdFromKey) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey_Result GetRecIdFromKey(AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Create_Result Create(AMP_SalesOrderManager.sr_InvDiscDetails.Create request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Create_Result> CreateAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple_Result CreateMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple_Result> CreateMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Update_Result Update(AMP_SalesOrderManager.sr_InvDiscDetails.Update request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Update_Result> UpdateAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple_Result UpdateMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang mehrere Rückgabewerte aufweist.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple_Result> UpdateMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappername (Delete_Result) von Nachricht "Delete_Result" nicht mit dem Standardwert (Delete) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Delete_Result Delete(AMP_SalesOrderManager.sr_InvDiscDetails.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Delete_Result> DeleteAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails")]
    public partial class RechnungsrabattDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string fORMAT_Record_IDField;
        
        private string discount_CodeField;
        
        private int discount_PositionField;
        
        private bool discount_PositionFieldSpecified;
        
        private string discount_DescriptionField;
        
        private decimal discount_PercentField;
        
        private bool discount_PercentFieldSpecified;
        
        private decimal discount_AmountField;
        
        private bool discount_AmountFieldSpecified;
        
        private decimal new_Base_discountField;
        
        private bool new_Base_discountFieldSpecified;
        
        private bool decrease_Commission_BaseField;
        
        private bool decrease_Commission_BaseFieldSpecified;
        
        private bool discount_fixed_net_priceField;
        
        private bool discount_fixed_net_priceFieldSpecified;
        
        private decimal commissionBaseAmountField;
        
        private bool commissionBaseAmountFieldSpecified;
        
        private decimal totalDiscAmountField;
        
        private bool totalDiscAmountFieldSpecified;
        
        private decimal newSubTotalField;
        
        private bool newSubTotalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FORMAT_Record_ID {
            get {
                return this.fORMAT_Record_IDField;
            }
            set {
                this.fORMAT_Record_IDField = value;
                this.RaisePropertyChanged("FORMAT_Record_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Discount_Code {
            get {
                return this.discount_CodeField;
            }
            set {
                this.discount_CodeField = value;
                this.RaisePropertyChanged("Discount_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Discount_Position {
            get {
                return this.discount_PositionField;
            }
            set {
                this.discount_PositionField = value;
                this.RaisePropertyChanged("Discount_Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Discount_PositionSpecified {
            get {
                return this.discount_PositionFieldSpecified;
            }
            set {
                this.discount_PositionFieldSpecified = value;
                this.RaisePropertyChanged("Discount_PositionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Discount_Description {
            get {
                return this.discount_DescriptionField;
            }
            set {
                this.discount_DescriptionField = value;
                this.RaisePropertyChanged("Discount_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Discount_Percent {
            get {
                return this.discount_PercentField;
            }
            set {
                this.discount_PercentField = value;
                this.RaisePropertyChanged("Discount_Percent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Discount_PercentSpecified {
            get {
                return this.discount_PercentFieldSpecified;
            }
            set {
                this.discount_PercentFieldSpecified = value;
                this.RaisePropertyChanged("Discount_PercentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Discount_Amount {
            get {
                return this.discount_AmountField;
            }
            set {
                this.discount_AmountField = value;
                this.RaisePropertyChanged("Discount_Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Discount_AmountSpecified {
            get {
                return this.discount_AmountFieldSpecified;
            }
            set {
                this.discount_AmountFieldSpecified = value;
                this.RaisePropertyChanged("Discount_AmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal New_Base_discount {
            get {
                return this.new_Base_discountField;
            }
            set {
                this.new_Base_discountField = value;
                this.RaisePropertyChanged("New_Base_discount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool New_Base_discountSpecified {
            get {
                return this.new_Base_discountFieldSpecified;
            }
            set {
                this.new_Base_discountFieldSpecified = value;
                this.RaisePropertyChanged("New_Base_discountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool Decrease_Commission_Base {
            get {
                return this.decrease_Commission_BaseField;
            }
            set {
                this.decrease_Commission_BaseField = value;
                this.RaisePropertyChanged("Decrease_Commission_Base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Decrease_Commission_BaseSpecified {
            get {
                return this.decrease_Commission_BaseFieldSpecified;
            }
            set {
                this.decrease_Commission_BaseFieldSpecified = value;
                this.RaisePropertyChanged("Decrease_Commission_BaseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Discount_fixed_net_price {
            get {
                return this.discount_fixed_net_priceField;
            }
            set {
                this.discount_fixed_net_priceField = value;
                this.RaisePropertyChanged("Discount_fixed_net_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Discount_fixed_net_priceSpecified {
            get {
                return this.discount_fixed_net_priceFieldSpecified;
            }
            set {
                this.discount_fixed_net_priceFieldSpecified = value;
                this.RaisePropertyChanged("Discount_fixed_net_priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal CommissionBaseAmount {
            get {
                return this.commissionBaseAmountField;
            }
            set {
                this.commissionBaseAmountField = value;
                this.RaisePropertyChanged("CommissionBaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommissionBaseAmountSpecified {
            get {
                return this.commissionBaseAmountFieldSpecified;
            }
            set {
                this.commissionBaseAmountFieldSpecified = value;
                this.RaisePropertyChanged("CommissionBaseAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal TotalDiscAmount {
            get {
                return this.totalDiscAmountField;
            }
            set {
                this.totalDiscAmountField = value;
                this.RaisePropertyChanged("TotalDiscAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalDiscAmountSpecified {
            get {
                return this.totalDiscAmountFieldSpecified;
            }
            set {
                this.totalDiscAmountFieldSpecified = value;
                this.RaisePropertyChanged("TotalDiscAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal NewSubTotal {
            get {
                return this.newSubTotalField;
            }
            set {
                this.newSubTotalField = value;
                this.RaisePropertyChanged("NewSubTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewSubTotalSpecified {
            get {
                return this.newSubTotalFieldSpecified;
            }
            set {
                this.newSubTotalFieldSpecified = value;
                this.RaisePropertyChanged("NewSubTotalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails")]
    public partial class RechnungsrabattDetails_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RechnungsrabattDetails_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RechnungsrabattDetails_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails")]
    public enum RechnungsrabattDetails_Fields {
        
        /// <remarks/>
        FORMAT_Record_ID,
        
        /// <remarks/>
        Discount_Code,
        
        /// <remarks/>
        Discount_Position,
        
        /// <remarks/>
        Discount_Description,
        
        /// <remarks/>
        Discount_Percent,
        
        /// <remarks/>
        Discount_Amount,
        
        /// <remarks/>
        New_Base_discount,
        
        /// <remarks/>
        Decrease_Commission_Base,
        
        /// <remarks/>
        Discount_fixed_net_price,
        
        /// <remarks/>
        CommissionBaseAmount,
        
        /// <remarks/>
        TotalDiscAmount,
        
        /// <remarks/>
        NewSubTotal,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public int Discount_Position;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=1)]
        public string Discount_Code;
        
        public Read() {
        }
        
        public Read(int Discount_Position, string Discount_Code) {
            this.Discount_Position = Discount_Position;
            this.Discount_Code = Discount_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails;
        
        public Read_Result() {
        }
        
        public Read_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            this.RechnungsrabattDetails = RechnungsrabattDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            this.RechnungsrabattDetails = RechnungsrabattDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails;
        
        public Create() {
        }
        
        public Create(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            this.RechnungsrabattDetails = RechnungsrabattDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails;
        
        public Create_Result() {
        }
        
        public Create_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            this.RechnungsrabattDetails = RechnungsrabattDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List) {
            this.RechnungsrabattDetails_List = RechnungsrabattDetails_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List) {
            this.RechnungsrabattDetails_List = RechnungsrabattDetails_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails;
        
        public Update() {
        }
        
        public Update(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            this.RechnungsrabattDetails = RechnungsrabattDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails;
        
        public Update_Result() {
        }
        
        public Update_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            this.RechnungsrabattDetails = RechnungsrabattDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List) {
            this.RechnungsrabattDetails_List = RechnungsrabattDetails_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List) {
            this.RechnungsrabattDetails_List = RechnungsrabattDetails_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/rechnungsrabattdetails", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RechnungsrabattDetails_PortChannel : AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RechnungsrabattDetails_PortClient : System.ServiceModel.ClientBase<AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port>, AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port {
        
        public RechnungsrabattDetails_PortClient() {
        }
        
        public RechnungsrabattDetails_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RechnungsrabattDetails_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RechnungsrabattDetails_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RechnungsrabattDetails_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Read_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.Read(AMP_SalesOrderManager.sr_InvDiscDetails.Read request) {
            return base.Channel.Read(request);
        }
        
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails Read(int Discount_Position, string Discount_Code) {
            AMP_SalesOrderManager.sr_InvDiscDetails.Read inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.Read();
            inValue.Discount_Position = Discount_Position;
            inValue.Discount_Code = Discount_Code;
            AMP_SalesOrderManager.sr_InvDiscDetails.Read_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).Read(inValue);
            return retVal.RechnungsrabattDetails;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Read_Result> AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.ReadAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Read_Result> ReadAsync(int Discount_Position, string Discount_Code) {
            AMP_SalesOrderManager.sr_InvDiscDetails.Read inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.Read();
            inValue.Discount_Position = Discount_Position;
            inValue.Discount_Code = Discount_Code;
            return ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.ReadByRecId(AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails ReadByRecId(string recId) {
            AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId();
            inValue.recId = recId;
            AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).ReadByRecId(inValue);
            return retVal.RechnungsrabattDetails;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId_Result> AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.ReadByRecIdAsync(AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.ReadByRecId();
            inValue.recId = recId;
            return ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.ReadMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] ReadMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Filter[] filter, string bookmarkKey, int setSize) {
            AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple_Result> AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.ReadMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple_Result> ReadMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Filter[] filter, string bookmarkKey, int setSize) {
            AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.IsUpdated(AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated();
            inValue.Key = Key;
            AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated_Result> AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.IsUpdatedAsync(AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated_Result> IsUpdatedAsync(string Key) {
            AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.IsUpdated();
            inValue.Key = Key;
            return ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.GetRecIdFromKey(AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey();
            inValue.Key = Key;
            AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey_Result> AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.GetRecIdFromKeyAsync(AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.GetRecIdFromKey();
            inValue.Key = Key;
            return ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Create_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.Create(AMP_SalesOrderManager.sr_InvDiscDetails.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            AMP_SalesOrderManager.sr_InvDiscDetails.Create inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.Create();
            inValue.RechnungsrabattDetails = RechnungsrabattDetails;
            AMP_SalesOrderManager.sr_InvDiscDetails.Create_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).Create(inValue);
            RechnungsrabattDetails = retVal.RechnungsrabattDetails;
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Create_Result> CreateAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.CreateMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List) {
            AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple();
            inValue.RechnungsrabattDetails_List = RechnungsrabattDetails_List;
            AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).CreateMultiple(inValue);
            RechnungsrabattDetails_List = retVal.RechnungsrabattDetails_List;
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple_Result> CreateMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Update_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.Update(AMP_SalesOrderManager.sr_InvDiscDetails.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails RechnungsrabattDetails) {
            AMP_SalesOrderManager.sr_InvDiscDetails.Update inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.Update();
            inValue.RechnungsrabattDetails = RechnungsrabattDetails;
            AMP_SalesOrderManager.sr_InvDiscDetails.Update_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).Update(inValue);
            RechnungsrabattDetails = retVal.RechnungsrabattDetails;
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Update_Result> UpdateAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.UpdateMultiple(AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails[] RechnungsrabattDetails_List) {
            AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple();
            inValue.RechnungsrabattDetails_List = RechnungsrabattDetails_List;
            AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).UpdateMultiple(inValue);
            RechnungsrabattDetails_List = retVal.RechnungsrabattDetails_List;
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple_Result> UpdateMultipleAsync(AMP_SalesOrderManager.sr_InvDiscDetails.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMP_SalesOrderManager.sr_InvDiscDetails.Delete_Result AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.Delete(AMP_SalesOrderManager.sr_InvDiscDetails.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            AMP_SalesOrderManager.sr_InvDiscDetails.Delete inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.Delete();
            inValue.Key = Key;
            AMP_SalesOrderManager.sr_InvDiscDetails.Delete_Result retVal = ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Delete_Result> AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port.DeleteAsync(AMP_SalesOrderManager.sr_InvDiscDetails.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMP_SalesOrderManager.sr_InvDiscDetails.Delete_Result> DeleteAsync(string Key) {
            AMP_SalesOrderManager.sr_InvDiscDetails.Delete inValue = new AMP_SalesOrderManager.sr_InvDiscDetails.Delete();
            inValue.Key = Key;
            return ((AMP_SalesOrderManager.sr_InvDiscDetails.RechnungsrabattDetails_Port)(this)).DeleteAsync(inValue);
        }
    }
}
