<?xml version="1.0" encoding="utf-8"?><Database Name="Abfragedaten_BC" Class="LinqToSqlDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NAV_DB\NAVISION;Initial Catalog=Abfragedaten_BC;Integrated Security=True" SettingsObjectName="AMP_SalesOrderManager.Properties.Settings" SettingsPropertyName="Abfragedaten_BCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AMP_SalesOrderMng_OrderList" Member="AMP_SalesOrderMng_OrderList">
    <Type Name="AMP_SalesOrderMng_OrderList">
      <Column Name="Auftragsnr" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AMP_SalesOrderMng_OrderListDetail" Member="AMP_SalesOrderMng_OrderListDetail">
    <Type Name="AMP_SalesOrderMng_OrderListDetail">
      <Column Name="Auftragsnr" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ländercode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ImportString" Type="System.String" DbType="NVarChar(222)" CanBeNull="true" />
      <Column Name="[Record ID]" Member="Record_ID" Type="System.Data.Linq.Binary" DbType="VarBinary(448)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Record ID Text]" Member="Record_ID_Text" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="splitTZ" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="TZDiscountPosition" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TZDiscountCode" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[Discount _]" Member="Discount__" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="splitNP" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NetPriceDiscountCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NetPriceDiscountPosition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NetPriceNewNetPrice" Type="System.Decimal" DbType="Decimal(38,18) NOT NULL" CanBeNull="false" />
      <Column Name="splitTC" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="TransportLineNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransportLineDescription" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="TransportNewUnitPrice" Type="System.Decimal" DbType="Decimal(38,18) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>