#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP_SalesOrderManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Abfragedaten_BC")]
	public partial class LinqToSqlDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    #endregion
		
		public LinqToSqlDataClassesDataContext() : 
				base(global::AMP_SalesOrderManager.Properties.Settings.Default.Abfragedaten_BCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AMP_SalesOrderMng_InvDiscDetail> AMP_SalesOrderMng_InvDiscDetail
		{
			get
			{
				return this.GetTable<AMP_SalesOrderMng_InvDiscDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AMP_SalesOrderMng_InvDiscDetail")]
	public partial class AMP_SalesOrderMng_InvDiscDetail
	{
		
		private int _id;
		
		private string _Auftragsnr;
		
		private string _Importstring;
		
		private string _RecordIDText;
		
		public AMP_SalesOrderMng_InvDiscDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auftragsnr", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Auftragsnr
		{
			get
			{
				return this._Auftragsnr;
			}
			set
			{
				if ((this._Auftragsnr != value))
				{
					this._Auftragsnr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importstring", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Importstring
		{
			get
			{
				return this._Importstring;
			}
			set
			{
				if ((this._Importstring != value))
				{
					this._Importstring = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordIDText", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RecordIDText
		{
			get
			{
				return this._RecordIDText;
			}
			set
			{
				if ((this._RecordIDText != value))
				{
					this._RecordIDText = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
